### PR TITLE
Add TextEditor test to check for initial value equality

### PR DESCRIPTION
**Pull request by mjoyce91**
#864

### CODE REVIEW

**Comment by jseppi** [comment]
Can you test that they are the expected values after clicking submit and cancel? Basically what I was trying to get at was testing that clicking submit or cancel results in passing the correct `editorState` prop down to the `Editor` component.

**Comment by mjoyce91** [comment]
@jseppi - ah I see what you mean. Mocking the way that draftjs forms immutable objects might be tricky, but I'll add a test to ensure that `editorState` and `editorStateCopy` match after invoking `submit` or `cancel`.

**Comment by jseppi** [comment]
hrm, could you grab the `Editor` and check its props?

Something like 

```js
// after cancel
expect(wrapper.find('Editor').props('editorState')).toBe(originalEditorState);

// after submit
expect(wrapper.find('Editor').props('editorState')).toBe(newEditorState);
```

**Comment by mjoyce91** [comment]
beat me to it

**Comment by mjoyce91** [comment]
I check for inequality initially just as a sanity check

**Comment by burgwyn** [comment]
Guys... 🎃

**Comment by jseppi** [comment]
We don’t want to be haunted by the spectre of spoooooky tests!

**Comment by mjoyce91** [comment]
Weird, if I run a wrapper.find('Editor'), I get `Method “props” is only meant to be run on a single node. 0 found instead.`, but if I throw an `id="a"` on `<Editor>`, I can find by `"#a"`.

**Comment by jseppi** [comment]
That's odd o_O
You can do `console.log(wrapper.debug())` to see exactly what the wrapper looks like.

**Comment by mjoyce91** [comment]
Weird, its name changes to `PluginEditor`.

**Pull request merged**
