### PR TITLE
- Workaround for redux dispatch function prop causing all instances o…

### LINKED ISSUE #1351: Favoriting and Adding to Bid List feel unresponsive
### Steps to reproduce the issue (please be as specific as possible)
Click on the ⭐️ icon to make a position a favorite (or not-favorite).
Click on Add to Bid List to add a position to your bid list.

### Expected behavior
The icon toggles to favorite/not-favorite state quickly.
The Add to Bid List button response quickly.

### Actual behavior
There is a noticeable delay in the icon state changing.

favorite-slow

### Suggestions
- What if we toggle the visual state _first_ before all the async actions are complete? Then, if the async actions fail (for any reason -- network error, too many in bid list, etc), we can revert the visual state. I'm not sure if that UX is great or not
- Show a spinner or some other loading state if the async actions take more than `THRESHOLD ms`

### PR DESCRIPTION
**Pull request by Icemanbeta**
- Workaround for redux dispatch function prop causing all instances of `Favorite` component to re-render by adding a `shouldComponentUpdate` hook.

### CODE REVIEW

**Comment by Icemanbeta** [comment]
Check https://github.com/18F/State-TalentMAP/issues/1351#issuecomment-372083753

**Comment by mjoyce91** [comment]
This looks good. I think we should still implement some kind of UI, as you mention in https://github.com/18F/State-TalentMAP/issues/1351#issuecomment-372083753. I think this could either be a spinner, or we could simply change the state, and revert it should an AJAX error occur.

**Comment by Icemanbeta** [comment]
If an ajax error occurs, the component wouldn't render the active flag I dont think because the component always rerenders based on the `compareArray`. 

Roger that on the loading UI I'll update this

**Comment by Icemanbeta** [comment]
- Add loading spinner UI to `Favorite` - https://github.com/18F/State-TalentMAP/issues/1351#issuecomment-37247499

**Comment by Icemanbeta** [comment]
- Tweaked `Favorite` container when child of `ResultCard` - https://github.com/18F/State-TalentMAP/issues/1351#issuecomment-372516644 😄

**Comment by burgwyn** [comment]
@Icemanbeta - run `yarn test -u` - it will regenerate the snapshots with the latest changes.  More info [here](https://facebook.github.io/jest/docs/en/snapshot-testing.html)

**Pull request merged**
