### PR TITLE
4 Month Demo -> Staging

### PR DESCRIPTION
**Pull request by burgwyn**
Capturing a series of smaller edits to build out our 4 month demo

- Adding first pass at interactive map
- Label: Writing -> Reading
- Label: Popular -> Highlighted
- Search Filters - minor edits

### CODE REVIEW

**Comment by jseppi** [comment]
@burgwyn: any ideas what these hanging codeclimate status checks are from? They seem to be happening consistently. I checked the workflow build and it does look like the coverage result is being reported, but I guess the actual codeclimate style/lint checks are for some reason not running.

**Comment by burgwyn** [comment]
```
c02p71npg3qp:State-TalentMAP nathanielburgwyn$ codeclimate analyze
Starting analysis
Running eslint: Done!
Running scss-lint: Done!

Analysis complete! Found 0 issues.
```

**Comment by mjoyce91** [comment]
Can confirm results as well:

```
michaels-mbp:State-TalentMAP-copy4 michaeljoyce$ git branch | grep \*
* dev
michaels-mbp:State-TalentMAP-copy4 michaeljoyce$ codeclimate analyze
Starting analysis
Running eslint: Done!
Running scss-lint: Done!

Analysis complete! Found 0 issues.
```

**Comment by burgwyn** [comment]
I think this is the CodeClimate rule in GitHub and not CircleCI.  Not 100% certain though.

**Comment by jseppi** [comment]
Confirming that the CodeClimate check passes locally. I will admin merge this PR.

**Pull request merged**
