### PR TITLE
staging -> master

### PR DESCRIPTION
**Pull request by burgwyn**
This includes Sprints 6 & 7

### CODE REVIEW

**Comment by jseppi** [comment]
Something is definitely up with CodeClimate. It's hanging on this one also. Maybe the payload is too large for them to process?

**Comment by burgwyn** [comment]
```
c02p71npg3qp:State-TalentMAP nathanielburgwyn$ git checkout staging
Branch staging set up to track remote branch staging from origin.
Switched to a new branch 'staging'
c02p71npg3qp:State-TalentMAP nathanielburgwyn$ git pull origin
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), done.
From github.com:18F/State-TalentMAP
   2013c55..f452e44  sprint-9   -> origin/sprint-9
Already up-to-date.
c02p71npg3qp:State-TalentMAP nathanielburgwyn$ codeclimate analyze
Starting analysis
Running eslint: Done!
Running scss-lint: Done!

Analysis complete! Found 0 issues.
```

**Comment by burgwyn** [comment]
CodeClimate seems fine locally on `staging`

**Comment by mjoyce91** [comment]
Can confirm results as well:

```
michaels-mbp:State-TalentMAP-copy4 michaeljoyce$ git branch | grep \*
* staging
michaels-mbp:State-TalentMAP-copy4 michaeljoyce$ codeclimate analyze
Starting analysis
Running eslint: Done!
Running scss-lint: Done!

Analysis complete! Found 0 issues.
```

**Comment by jseppi** [comment]
Same for me. But it seems like the check is consistently hanging on all PRs where it is triggered, so I wonder what the issue is.
I looked at the webhooks and they all look like they're being delivered.

**Comment by burgwyn** [comment]
Is it just the protected branches?

**Comment by jseppi** [comment]
Hrm, it did work over in `Sprint 8 -> dev`: https://github.com/18F/State-TalentMAP/pull/683

Maybe just a fluke with their service?

**Comment by jseppi** [comment]
I will admin merge this PR given that the CodeClimate checks pass locally.

**Pull request merged**
