### PR TITLE
Remove the standalone Bid List page

### PR DESCRIPTION
**Pull request by mjoyce91**
Removes the standalone Bid List page and related components/containers/links, as we've migrated away from this page to the Bid Tracker.

Closes https://github.com/18F/State-TalentMAP/issues/1314

### CODE REVIEW

**Comment by burgwyn** [comment]
We need this against `release-candidate-1` too

**Comment by mjoyce91** [comment]
@burgwyn - what's the best way to merge release-candidate-specific work? What if we tracked work in three buckets: 1. Release-candidate work, 2. Work for both, 3. Non-release-candidate work. Then we wouldn't need to create duplicate PRs for each individual feature.

**Comment by burgwyn** [comment]
I was looking to tag issues with product vs release candidate (or both).  I think we can save feature branches, re-base and re-PR.  It doesn’t solve the multiple PR problem, but it would let us isolate at the issue level.

**Comment by mjoyce91** [comment]
It looks like I accidentally removed the Bid Tracker here as well. We'll want to remove that for `release-candidate-1`, but not our main branch.

**Pull request merged**
